import type { Book, User, Student } from "@/types";

export const users: User[] = [
  {
    id: "user-1",
    name: "Admin User",
    email: "admin@deogiri.ac.in",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?u=admin",
  },
  {
    id: "user-2",
    name: "Librarian User",
    email: "librarian@deogiri.ac.in",
    role: "librarian",
    avatar: "https://i.pravatar.cc/150?u=librarian",
  },
];

// This `students` array is now deprecated in favor of Firestore.
// It can be used for reference or removed.
export const students: Student[] = [
    {
        id: "user-3",
        studentId: "2526123456",
        name: "Student User",
        email: "student@deogiri.ac.in",
        role: "student",
        avatar: "https://i.pravatar.cc/150?u=student",
        fines: 15,
        department: "Faculty of Science & I.T.",
        course: "B.Sc. CS",
        contactNumber: "9876543210",
        yearOfStudy: "2nd",
        borrowHistory: [
            { bookId: "book-1", borrowDate: "2024-04-01", returnDate: "2024-04-15", dueDate: "2024-04-14", fine: 10 },
            { bookId: "book-2", borrowDate: "2024-05-10", dueDate: "2024-05-24" },
            { bookId: "book-5", borrowDate: "2024-03-20", returnDate: "2024-04-02", dueDate: "2024-04-03" },
        ]
    },
    {
        id: "user-4",
        studentId: "2526789012",
        name: "Jane Doe",
        email: "jane.d@deogiri.ac.in",
        role: "student",
        avatar: "https://i.pravatar.cc/150?u=jane",
        fines: 0,
        department: "Faculty of Commerce & Management",
        course: "BBA",
        contactNumber: "9876543211",
        yearOfStudy: "1st",
        borrowHistory: [
            { bookId: "book-3", borrowDate: "2024-05-01", dueDate: "2024-05-15" },
        ]
    },
     {
        id: "user-5",
        studentId: "2526345678",
        name: "John Smith",
        email: "john.s@deogiri.ac.in",
        role: "student",
        avatar: "https://i.pravatar.cc/150?u=john",
        fines: 0,
        department: "Faculty of Arts & Social Science",
        course: "BA",
        contactNumber: "9876543212",
        yearOfStudy: "3rd",
        borrowHistory: []
    },
]

export const books: Book[] = [
  {
    id: "book-1",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0-06-112008-4",
    category: "Classic",
    department: "BA",
    publicationYear: 1960,
    totalCopies: 5,
    availableCopies: 2,
    coverImage: "https://picsum.photos/seed/book1/300/450",
    coverImageHint: "book cover",
  },
  {
    id: "book-2",
    title: "Dune",
    author: "Frank Herbert",
    isbn: "978-0-441-01359-3",
    category: "Sci-Fi",
    department: "BCS.IT",
    publicationYear: 1965,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "https://picsum.photos/seed/book2/300/450",
    coverImageHint: "space stars",
  },
  {
    id: "book-3",
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    isbn: "978-0-553-10354-0",
    category: "Fantasy",
    department: "BA",
    publicationYear: 1996,
    totalCopies: 10,
    availableCopies: 0,
    coverImage: "https://picsum.photos/seed/book3/300/450",
    coverImageHint: "fantasy dragon",
  },
  {
    id: "book-4",
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    isbn: "978-0-140-43786-6",
    category: "Mystery",
    department: "BA",
    publicationYear: 1902,
    totalCopies: 3,
    availableCopies: 3,
    coverImage: "https://picsum.photos/seed/book4/300/450",
    coverImageHint: "mystery clue",
  },
  {
    id: "book-5",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "978-0-06-231609-7",
    category: "History",
    department: "B.COM",
    publicationYear: 2011,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "https://picsum.photos/seed/book5/300/450",
    coverImageHint: "history scroll",
  },
  {
    id: "book-6",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    isbn: "978-1-4516-4853-9",
    category: "Biography",
    department: "BCA",
    publicationYear: 2011,
    totalCopies: 4,
    availableCopies: 1,
    coverImage: "https://picsum.photos/seed/book6/300/450",
    coverImageHint: "person portrait",
  },
  {
    id: "book-7",
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    isbn: "978-0-399-22690-8",
    category: "Children",
    publicationYear: 1969,
    totalCopies: 12,
    availableCopies: 12,
    coverImage: "https://picsum.photos/seed/book7/300/450",
    coverImageHint: "cartoon animal",
  },
  {
    id: "book-8",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "978-0-141-43951-8",
    category: "Romance",
    department: "BA",
    publicationYear: 1813,
    totalCopies: 7,
    availableCopies: 7,
    coverImage: "https://picsum.photos/seed/book8/300/450",
    coverImageHint: "couple heart",
  },
];
