
// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit.

export const firebaseConfig = {
  "projectId": "studio-8921495996-9da38",
  "appId": "1:441739353153:web:2b8b1789e73cfe77cb3ac0",
  "apiKey": "AIzaSyCT6xO379Mf7gL2kuzTAv0G7FQe2uTq_uY",
  "authDomain": "studio-8921495996-9da38.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "441739353153"
};
