
// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit.

export const firebaseConfig = {
  apiKey: "AIzaSyC8JaIfHXULD51fVMD6oPt5okw9oG1XiHk",
  authDomain: "deogiri-library-management.firebaseapp.com",
  projectId: "deogiri-library-management",
  storageBucket: "deogiri-library-management.firebasestorage.app",
  messagingSenderId: "815544549011",
  appId: "1:815544549011:web:4df5b52aa71a3e37d9d766",
  measurementId: "G-XEHL54H17H"
};
